import React from "react";
import { useEffect } from "react";
import { useState } from "react";
import { Loader, Card, FormField } from "../components";
const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};
function Home() {
  const [loading, SetLoading] = useState(false);
  const [allPosts, SetAllPosts] = useState(null);
  const [searchText, SetSearchText] = useState("");
  const [searchTimeout, SetSearchTimeout] = useState(null);
  const [searchedResults, SetSearchedResults] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      SetLoading(true);

      try {
        const response = await fetch("http://localhost:8080/api/v1/post", {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        });

        if (response.ok) {
          const result = await response.json();
          SetAllPosts(result.data.reverse());
        }
      } catch (err) {
        alert(err);
      } finally {
        SetLoading(false);
      }
    };
    fetchPosts();
  }, []);
  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    SetSearchText(e.target.value);

    SetSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter(
          (item) =>
            item.name.toLowerCase().includes(searchText.toLowerCase()) ||
            item.prompt.toLowerCase().includes(searchText.toLowerCase())
        );
        SetSearchedResults(searchResult);
      }, 500)
    );
  };

  return (
    <div>
      <section className="max-w-7xl max-auto">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
            Browse through a collection of imaginative and visually stunning
            images generated by DALL-E AI
          </p>
        </div>
        <div className="mt-16">
          <FormField
            labelName="Search posts"
            type="text"
            name="text"
            placeholder="Search something..."
            value={searchText}
            handleChange={handleSearchChange}
          />
        </div>
        <div className="mt-10 ">
          {loading ? (
            <div className="flex justify-center items-center">
              <Loader></Loader>
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className="font-medium text-[#666e75] text-xl mb-3">
                  Showing results for
                  <span className="text-[#222328]">{searchText}</span>:
                </h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                {searchText ? (
                  <RenderCards data={searchedResults} title="noresult"></RenderCards>
                ) : (
                  <>
                    <RenderCards data={allPosts} title="no post"></RenderCards>
                  </>
                )}
              </div>
            </>
          )}
        </div>
      </section>
    </div>
  );
}

export default Home;
